<a href="https://colab.research.google.com/github/Lab-of-Infinity/PyTorch-for-Computer-Vision/blob/main/PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **What is PyTorch?**
**PyTorch is a Python-based library which facilitates building Deep Learning models and using them in various applications. But this is more than just another Deep Learning library. It’s a scientific computing package (as the official PyTorch documents state).**

It’s a Python-based scientific computing package targeted at two sets of audiences:
1. A replacement for NumPy to use the power of GPUs
2. A deep learning research platform that provides maximum flexibility and speed

We mentioned PyTorch is the perfect choice for the first deep learning library you should learn. 

In this section, we will elaborate on why it is so.

There is no shortage of Deep Learning libraries: Keras, Tensorflow, Caffe, Theano (RIP) and many more. What makes PyTorch different?

- ***An ideal deep learning library should be easy to learn and use, flexible enough to be used in various applications, efficient so that we can deal with huge real-life datasets and accurate enough to provide correct results even in presence of uncertainty in input data.***

- ***PyTorch performs really well on all these metrics mentioned above. The “pythonic” coding style makes it simple to learn and use. GPU acceleration, support for distributed computing and automatic gradient calculation helps in performing backward pass automatically starting from a forward expression.***

- ***Of course, because of Python, it faces a risk of slow runtime but the high-performance C++ API (libtorch) removes that overhead. This makes the transition from R&D to Production very smooth. One more reason to use PyTorch!***

Reference Link : https://learnopencv.com/pytorch-for-beginners-basics/

## Overview of the PyTorch Library

Now that we are aware of PyTorch and what makes it unique, let’s have a look at the basic pipeline of a PyTorch project. The figure below describes a typical workflow along with the important modules associated with each step.

###Torch Pipeline
Basic PyTorch Workflow
The important PyTorch modules that we are going to briefly discuss here are: torch.nn, torch.optim, torch.utils and torch.autograd.

#### 1. Data Loading and Handling
The very first step in any deep learning project deals with data loading and handling. PyTorch provides utilities for the same via torch.utils.data.

The two important classes in this module are Dataset and DataLoader.

  - Dataset is built on top of Tensor data type and is used primarily for custom datasets.
  - DataLoader is used when you have a large dataset and you want to load data from a Dataset in background so that it’s ready and waiting for the training loop.
We can also use torch.nn.DataParallel and torch.distributed if we have access to multiple machines or GPUs.

#### 2. Building Neural Network
The torch.nn module is used for creating Neural Networks. It provides all the common neural network layers such as fully connected layers, convolutional layers, activation and loss functions etc.

Once the network architecture is created and data is ready to be fed to the network, we need techniques to update the weights and biases so that the network starts to learn. These utilities are provided in torch.optim module. Similarly, for automatic differentiation which is required during backward pass, we use the torch.autograd module.

#### 3. Model Inference & Compatibility
After the model has been trained, it can be used to predict output for test cases or even new datasets. This process is referred to as model inference.

PyTorch also provides TorchScript which can be used to run models independently from a Python runtime. This can be thought of as a Virtual Machine with instructions mainly specific to Tensors.

You can also convert model trained using PyTorch into formats like ONNX, which allow you to use these models in other DL frameworks such as MXNet, CNTK, Caffe2. You can also convert onnx models to Tensorflow.

In [ ]:
import torch

In [ ]:
# create  tensor with just ones in a column
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
# Create a Tensor wih just zeros in a column
b = torch.zeros(5)
print(b)

tensor([0., 0., 0., 0., 0.])


In [ ]:
# Create a tensor with custom value
c = torch.tensor([1.0,2.0,3.0,4.0,5.0])
print(c)

tensor([1., 2., 3., 4., 5.])


Creating Higher dimensional Tensor

In [ ]:
d = torch.zeros(3,2)
print(d)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [ ]:
e= torch.ones(3,2)
print(e)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [ ]:
f = torch.tensor([[1.0,2.0],[3.0,4.0]])
print(f)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
# 3D Tensor
g = torch.tensor([[[1.,2.],[3.,4.]], [[5.,6.],[7.,8.]]])
print(g)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


- Shape of Tensor

In [ ]:
print(f.shape)

torch.Size([2, 2])


In [ ]:
print(e.shape)

torch.Size([3, 2])


In [ ]:
print(g.shape)

torch.Size([2, 2, 2])


- Access an element in Tensor

In [ ]:
print(c[2])

tensor(3.)


In [ ]:
# Get element at row 1, column 0
print(f[1,0])

tensor(3.)


In [ ]:
# We can also use the following
print(f[1][0])

tensor(3.)


In [ ]:
# Similarly for 3D Tensor
print(g[1,0,0])

tensor(5.)


In [ ]:
print(g[1][0][0])

tensor(5.)


But what if you wanted to access one entire row in a 2D Tensor? We can use the same syntax as we would use in NumPy Arrays.

In [ ]:
# All elements
print(f[:])

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
# All elements from index 1 to 2
print(c[1:3])

tensor([2., 3.])


In [ ]:
# All elements till index 4
print(c[:4])

tensor([1., 2., 3., 4.])


In [ ]:
# First Row
print(f[0,:])

tensor([1., 2.])


In [ ]:
# Second Column
print(f[:,1])

tensor([2., 4.])


#### Specify data type of elements
Whenever we create a tensor, PyTorch decides the data type of the elements of the tensor such that the data type can cover all the elements of the tensor. We can override this by specifying the data type while creating the tensor.

In [ ]:
int_tensor = torch.tensor([[1,2,3],[4,5,6]])
print(int_tensor.dtype)

torch.int64


In [ ]:
# What if we changed any one element to floating point number?
int_tensor = torch.tensor([[1,2,3],[4.,5,6]])
print(int_tensor.dtype)

torch.float32


In [ ]:
# This can be overridden as follows
int_tensor = torch.tensor([[1,2,3],[4.,5,6]], dtype = torch.int32)
print(int_tensor.dtype)

torch.int32


<ipython-input-25-eaffba5815fa>:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  int_tensor = torch.tensor([[1,2,3],[4.,5,6]], dtype = torch.int32)


### Tensor to/from NumPy Array

In [ ]:
import numpy as np
# tensor to array
f_numpy = f.numpy()
print(f_numpy)

[[1. 2.]
 [3. 4.]]


In [ ]:
# Array to Tensor
h = np.array([[8,7,6,5],[4,3,2,1]])

In [ ]:
h_tensor = torch.from_numpy(h)

In [ ]:
print(h_tensor)

tensor([[8, 7, 6, 5],
        [4, 3, 2, 1]])


### Arithmetic Operations on Tensors

In [ ]:
tensor1 = torch.tensor([[1,2,3],[4,5,6]])
tensor2 = torch.tensor([[-1,2,-3],[4,-5,6]])

In [ ]:
# Addition


In [ ]:
# Create tensor
tensor1 = torch.tensor([[1,2,3],[4,5,6]])
tensor2 = torch.tensor([[-1,2,-3],[4,-5,6]])
 
# Addition
print(tensor1+tensor2)
# We can also use
print(torch.add(tensor1,tensor2))
 
# tensor([[ 0,  4,  0],
#        [ 8,  0, 12]])
 
# Subtraction
print(tensor1-tensor2)
# We can also use
print(torch.sub(tensor1,tensor2))
 
# tensor([[ 2,  0,  6],
#        [ 0, 10,  0]])
 
# Multiplication
# Tensor with Scalar
print(tensor1 * 2)
# tensor([[ 2,  4,  6],
#        [ 8, 10, 12]])
 
# Tensor with another tensor
# Elementwise Multiplication
print(tensor1 * tensor2)
# tensor([[ -1,   4,  -9],
#        [ 16, -25,  36]])
 
# Matrix multiplication
tensor3 = torch.tensor([[1,2],[3,4],[5,6]])
print(torch.mm(tensor1,tensor3))
# tensor([[22, 28],
#        [49, 64]])
 
# Division
# Tensor with scalar
print(tensor1/2)
# tensor([[0, 1, 1],
#        [2, 2, 3]])
 
# Tensor with another tensor
# Elementwise division
print(tensor1/tensor2)
# tensor([[-1,  1, -1],
#        [ 1, -1,  1]])